FROM microsoft/dotnet:1.1.2-sdk

ENV DOTNET_USE_POLLING_FILE_WATCHER 1

COPY ./src/Voidwell.Auth/Voidwell.Auth.csproj /tmp/Voidwell.Auth.csproj

WORKDIR /tmp

RUN dotnet restore

WORKDIR /Voidwell.Auth

ENTRYPOINT dotnet watch run
