<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Compile Remove="GrantValidators\ResourceOwnerPassword\**" />
    <EmbeddedResource Remove="GrantValidators\ResourceOwnerPassword\**" />
    <None Remove="GrantValidators\ResourceOwnerPassword\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenIddict.AspNetCore" />
    <PackageReference Include="OpenIddict.Validation.AspNetCore" />
    <PackageReference Include="OpenIddict.Abstractions" />
  </ItemGroup>
    
  <ItemGroup>
    <ProjectReference Include="..\Voidwell.Auth.Data\Voidwell.Auth.Data.csproj" />
    <ProjectReference Include="..\Voidwell.Auth.UserManagement\Voidwell.Auth.UserManagement.csproj" />
  </ItemGroup>
</Project>
